### ISSUE TITLE
USER STORY: Attain Graphic Design Artwork

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-nextjs#133]
As a user, I will want to have art work displayed as I view the web app so I will have a visually appealing graphical user interface as I navigate the site.

Issues:
- [x] reach out to the art department.  - BC 
- [x] Reach out to graphic design department faculty. 
- [x] Attain a design from the chosen department that can be used in the left and right margins of our web app.
- [x] Design should have different clothing items that represent what could be found at Belinda's Closet such as dresses, shoes, shirts, hats, etc.

**Comment by bcko** [comment]
@taylorpapke 
I got in touch with the art department and received a contact information of a faculty in charge of graphic design. I will reach out to the faculty today.

**Comment by bcko** [comment]
@taylorpapke I reached out to the faculty in graphic design department. I will keep you all posted.

**Comment by taylorpapke** [comment]
Here is a downloadable copy of the pdf that was sent to the design team: [belindas-closet-designs.pdf](https://github.com/SeattleColleges/belindas-closet-nextjs/files/14390466/belindas-closet-designs.pdf)

**Comment by taylorpapke** [comment]
Here is a downloadable copy of the pdf that was received from the design department: [Collaboration Opportunity between App Dev and Graphic Design Department Ideation 1.pdf](https://github.com/SeattleColleges/belindas-closet-nextjs/files/14466625/Collaboration.Opportunity.between.App.Dev.and.Graphic.Design.Department.Ideation.1.pdf)
