### ISSUE TITLE
USER STORY: Edit Product Page

### ISSUE THREAD

**Issue by TroyFPV48** [SeattleColleges/belindas-closet-nextjs#139]
As an application developer, I will want to have a product page that is user-friendly and shows the products based on the client's specifications.

This will reorganize product categories (Shoes, Coat, Short, etc.) and size-types based on the product like XS, 7.5 US, XXL, etc, properly assigned. After the filter is made, the product page should display a preview of every item captured from the back-end (preview image, name, color, price, etc). 

[Relevant tutorial.](https://www.youtube.com/watch?v=ZFYj7OrTeEs)

To preview the product page during development stage, run "http://localhost:8080/product-page".

Task:
- [x] #179
- [x]  Product page will capture the data in the backend in order to display products.
- [x] #185

**Comment by nickolasram** [comment]
@TroyFPV48 I don't know how much work you've done already, but in the pull request I just made, category cards on the home page now link to a blank product category page that display nothing but the category title. You can use this category page if you want, or if you have already started working on your own, you or I can make the cards on the home page link to your new page instead. Also, I'm passing the chosen product category title from the home page to your page via a URL parameter right now, but I'll be using dynamic routing soon. So if you use the URL parameter to determine the category to display on your page, just be aware that will have to be slightly retooled in the future once dynamic routing is implemented.

**Comment by TroyFPV48** [comment]
Actually, I can use your page and keep in touch with you to figure out our direction for doing this. Thanks for the heads up! 

> @TroyFPV48 I don't know how much work you've done already, but in the pull request I just made, category cards on the home page now link to a blank product category page that display nothing but the category title. You can use this category page if you want, or if you have already started working on your own, you or I can make the cards on the home page link to your new page instead. Also, I'm passing the chosen product category title from the home page to your page via a URL parameter right now, but I'll be using dynamic routing soon. So if you use the URL parameter to determine the category to display on your page, just be aware that will have to be slightly retooled in the future once dynamic routing is implemented.

**Comment by nickolasram** [comment]
Just created a pull request that includes a slight update to the category page to use dynamic routing.
