### ISSUE TITLE
USER STORY: Creator's Page

### ISSUE THREAD

**Issue by krayzieeddi** [SeattleColleges/belindas-closet-nextjs#146]
As an app developer, I will want to create a creator's page for when they successfully login they will be routed to their own page to use on the app.

Issues:
- [ ] Create a placeholder creator's page
- [ ] Creators are routed to the creator's page when successfully logged in

**Comment by krayzieeddi** [comment]
I have made the placeholder creator's page but I have technical issue with my gpg key as it is being skipped or not registering when trying to commit via VS code as I currently cannot commit anything to my branch as I'm troubleshooting the issue.

**Comment by taylorpapke** [comment]
@krayzieeddi Did the issue get resolved? Please reach out to @Seiyaroo or I on Slack if you continue to have problems with this. There is some material we have available for this depending on what the specific commit issue is in terms of the gpg key.

**Comment by krayzieeddi** [comment]
Currently not yet but i will have time this weekend to troubleshoot
further. Worst case I'll contact Nicklas or BC.
