### ISSUE TITLE
Bug: Fix CI on Pull Request

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-nextjs#151]
CI is not triggering properly for updates to pull requests. We never updated nextjs repos with our fix for the other repos. Here is what we did to fix this for the android repo:

![Image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/94101953/daa3c56b-b7da-4ccb-ad12-82ac8a1ccd09)

**Comment by tinpham5614** [comment]
I'm working on this issue. I would like to learn CI/CD.
