### ISSUE TITLE
Sign-In Page: Implement Login Functionality

### ISSUE THREAD

**Issue by intisarosman1** [SeattleColleges/belindas-closet-nextjs#172]
As a developer, I'd like to implement login functionality so I can be able to login successfully when the submit button is pressed.

Related to [User Story #132 ](https://github.com/SeattleColleges/belindas-closet-nextjs/issues/132)

**Comment by tinpham5614** [comment]
@intisarosman1 Are you working on this issue? If not, I can work on it.

**Comment by intisarosman1** [comment]
> @intisarosman1 Are you working on this issue? If not, I can work on it.

I was going to but I think it may be best if you took on this issue! I can work on another issue.
