### ISSUE TITLE
Update Website Styling: Update the Navbar

### ISSUE THREAD

**Issue by nickolasram** [SeattleColleges/belindas-closet-nextjs#210]
This should be an update to the navbar to use Material UI for styling. I'll try to keep everything looking close to how it is now but there may be some slight differences.

**Comment by tinpham5614** [comment]
Is any progress being made on this issue?

**Comment by taylorpapke** [comment]
@nickolasram Can @tinpham5614 finish this issue with the branch that he has completed? We have another user story for sprint 3 that is waiting on this.
