### ISSUE TITLE
USER STORY: Product Page

### ISSUE THREAD

**Issue by tinpham5614** [SeattleColleges/belindas-closet-nextjs#230]
- As a developer, I will want to add buttons to allow users to access each product.
- A list of issues.
  - [x] #231
- Screenshots/gifs/videos/diagrams/other visual aids.
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/72054441/3d024376-222a-4cd6-938b-6d61fb431c59)

**Comment by taylorpapke** [comment]
We have 2 user stories for sprint 3 that are for the product page but they are for different issues. The other one is #224.

**Comment by tinpham5614** [comment]
@taylorpapke It was 2 different user stories, one for a general **product page** and one for an **individual product page**. I was a bit confused but it makes sense to me now.
