### ISSUE TITLE
USER STORY: Figma Sitemap/userflow diagram

### ISSUE THREAD

**Issue by IsaacJrTypes** [SeattleColleges/belindas-closet-nextjs#329]
As a developer, I want a high fidelity site map to better understand the website's flow. The diagram should reflect the current and ongoing state of the app.

- [ ] Use Figma to create a diagram of all of our pages and how users can navigate.

**Comment by IsaacJrTypes** [comment]
Here Are the Figma user flow and page wireframes of Belinda's closet in its current state. 
Please feel free to give me any feedback. I can also supply the figjam file and link to the project. 
[Belindas-User-Flow(Current).pdf](https://github.com/SeattleColleges/belindas-closet-nextjs/files/15343457/Belindas-User-Flow.Current.pdf)
[Belinda_Wireframe.pdf](https://github.com/SeattleColleges/belindas-closet-nextjs/files/15343458/Belinda_Wireframe.pdf)

**Comment by Robel-003** [comment]
Belinda's closet figma diagram 
* Diagram looks accurate to the flow of the application
* The legend description for each of the paths is accurate to what I see as I navigate Belinda’s web app 
* The rerouting to the homepage once a user creates an account is a good addition
* In the product detail view page, their’s a archive, edit, and delete functionality, would it help to have another input legend there
* The paths after the admin page are accurate and represent the routes well in the web application
* Minor things to consider:
    * Would it help to have another input legend for when a user resets their password?

**Comment by IsaacJrTypes** [comment]
Thanks for the feedback! Over the summer, I plan to write product development documents for both NSC events and Belinda's closet and will take this feedback into account.
