### ISSUE TITLE
USER STORY: Documentation - Update Wiki 3

### ISSUE THREAD

**Issue by Bejarano03** [SeattleColleges/belindas-closet-nextjs#333]
USER STORY: Documentation - Update Wiki 3

- As a developer, I will want to understand the CI/CD pipeline and how to troubleshoot.

- [x] Documentation of CI/CD pipeline

**Comment by tinpham5614** [comment]
To understand more about CI/CD, I spent some time researching and getting familiar with this area. 
Here are some docs I collected: [link here](https://nextjsdeployment.notion.site/CI-CD-Research-1c6becbfa60943c7b175b4fea698af5a)

**Comment by Bejarano03** [comment]
I created the wiki work on Notion. Please follow the link provided and let me know if I should add anything prior to closing this issue. 

Link: https://www.notion.so/17fc90874f5e4f07adb10f0e7fdf0017?v=4150e401fc6046c489a9b5747e99c0eb&p=6efb14404ad74f158bfa07fba77bd11e&pm=s
