### ISSUE TITLE
Dashboard Page: Detailed Figma mockup for the design of the dashboard page.

### ISSUE THREAD

**Issue by BradleyCharles** [SeattleColleges/belindas-closet-nextjs#380]
Related to issue #341 

[Link to Figma page](https://www.figma.com/design/yQHLPUfwOwlAj9gyBMlA85/Dashboard?m=auto&t=npXGtA6oDSJKeXAY-6). 
The page is semi-interactive so if you actually visit the page in Figma and click the play button in the top right to run the prototype you can see the buttons and arrows being highlighted as you hover over them.

If you need or just want an invite to the Belinda's Closet Figma page you should be able to join [here](https://www.figma.com/team_invite/redeem/ROzuu6VcDevbXt5RNv77O0). (Let me now if this doesn't work and I can add you by email)

![Screenshot 2024-05-16 144631](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/67434992/1590d950-5492-400e-b8a7-a9b6fe6b8f9e)

**Comment by JesseCaddell** [comment]
Really liking how this is turning out! Well done! Very professional looking 👍
