### ISSUE TITLE
CD set up & Dependabot 

### ISSUE THREAD

**Issue by brandondombrowsky** [SeattleColleges/belindas-closet-nextjs#4]
As an Automation Developer. I will want to make sure my team has a GitHub repo configuration that continuously deploys approved changes to the main branch, and then in turn deploys changes to the client's servers. Ideally I will employ a Dependabot. I will get in touch with the lead engineer should I have any questions or need support. I will utilize GitHub Actions for my CD.

Story Points: 6-12

**Comment by brandondombrowsky** [comment]
This Issue is complete, yes?

**Comment by taylorpapke** [comment]
This issue is outdated since we've moved to our new user story format.
