### ISSUE TITLE
Bug: Sign In button error

### ISSUE THREAD

**Issue by jonathonkindle** [SeattleColleges/belindas-closet-nextjs#400]
**Describe the bug**\
After a user signs into the site, the sign in button remains. 

**To Reproduce**\
1. Go to Belindas Closet
2. Click on Sign In
3. Sign In
4. After Sign In and redirect, the "sign in" button remains.

<img width="1920" alt="Screenshot 2024-05-23 at 8 20 06 PM" src="https://github.com/SeattleColleges/belindas-closet-nextjs/assets/46705433/eb89a347-3910-41c5-925e-dad9d4af8755">

**Expected behavior**\
After signing in, the sign in button should detect a signed in user and be changed to a sign out button. Once clicked, the sign out button should sign the user out and redirect back to the main page where the button now becomes a sign in button again.

**Desktop (please complete the following information):**\
 - OS: MacOS and Windows
 - Browser [Any]

**Additional context**\
Will be connected to the state management (ie. cookies and tokens).

**Story Points**\
5

**Comment by tinpham5614** [comment]
I'm wondering if we should remove the sign-in button from the navbar since we already have one on the Home page.
