### ISSUE TITLE
Add charts for the number of students to the weekly activity page under dashboard

### ISSUE THREAD

**Issue by Alzavio** [SeattleColleges/belindas-closet-nextjs#526]
https://www.figma.com/design/yQHLPUfwOwlAj9gyBMlA85/Dashboard?node-id=2001-3&t=JOQOOXLpt30AodZw-0

**Comment by JesseCaddell** [comment]
Closing this issue due to lack of engagement. If we feel this needs to be reopened please reach out to leadership.
